site_name: Airframe

theme:
  name: material
  features:
    - navigation.tabs

nav:
  - Homu: index.md
  - Fundamentals: index.md
  - Static Analysis: index.md
  - Fatigue: index.md
  - Damage Tolerance: index.md
  - Tools: index.md
  - Certification: index.md
